### ISSUE TITLE
FMLIndexedMessageCodec exception, via api.player.server.ServerPlayerAPI.onUpdateEntity

### ISSUE THREAD

**Issue by dries007** [dries007/DebugServerInfo#1]
Reported by bigrice1018 on CurseForge.

Stack trace:
[tbk4xhg7.txt](https://github.com/dries007/DebugServerInfo/files/905626/tbk4xhg7.txt)

**Comment by bigrice1018** [comment]
Minecraft Version: 1.10.2
Forge: 12.18.3.2254

[modlist.txt](https://github.com/dries007/DebugServerInfo/files/906082/modlist.txt)
Change the file format to html for a better view

**Comment by dries007** [comment]
Thanks, any more information? (Like: it always happens when .... ?) Because it looks like this may be a hard one to figure out...

**Comment by bigrice1018** [comment]
Like i said
I am a modpack creator and i need to test the pack stability
So i just press F3 and open the inventory 
And started to AFK to test the ram usage and other stuff
But multiple times i crashed after like 3~4 mins

**Comment by dries007** [comment]
Alright, Singleplayer or Multiplayer?

**Comment by bigrice1018** [comment]
Singleplayer

**Comment by dries007** [comment]
I think I've stop-gapped the issue cause I can't figure out how to actually fix it and why it happens.

**Comment by dries007** [comment]
OK, I finally think I fixed it. Turns out the issue was a bit more complex than initially thought.

**Comment by bigrice1018** [comment]
cool thx~ :D

2017-05-20 5:50 GMT+08:00 Dries007 <notifications@github.com>:
